import requests, json

payload = """{
  "channel": "EFORM",
  "tellerId": "",
  "accountNum": "",
  "branch": "63",
  "accountType": "2000",
  "subCat": "0001",
  "othersOpenAccReason": "",
  "othersSrcOfFund": "",
  "idNum": "32710623005227111",
  "idType": "0001",
  "customerName": "KUCING GARONG BELANG LIMA",
  "pob" : "MEXICO",
  "dateOfBirth": "1995-11-11",
  "motherMaidenName" : "MEOW",
  "email": "kaki.kucing@cat.com",
  "homePhone": "0021345678",
  "mobileNum": "0895123456789",
  "education": "S1",
  "hobby": "Lainnya",
  "openAccReason": "2",
  "srcOfFund": "1",
  "projDep": "1",
  "taxId": "1123456789012345",
  "customerAddress": "JL. buntu no 9",
  "rt": "9",
  "rw": "8",
  "kelurahan": "z",
  "kecamatan": "x",
  "city": "cccc",
  "province": "ccs",
  "postalCode": "10210",
  "job": "09",
  "yearlyIncome": "1",
  "companyName": "aaaa",
  "companyAddress": "cdccc",
  "companyAddress2": "dddd",
  "officePostalCode": "11111",
  "jobTitle": "MLNT",
  "startWorkDate": "",
  "officePhone": "00318283932",
  "patronName": "TOM",
  "patronIdType": "1",
  "patronIdNum": "0987654321123456",
  "patronTaxId": "098765432112345",
  "patronAddress": "aaaaaaaaaaaaaaaa",
  "patronRt": "1",
  "patronRw": "333",
  "patronBuilding": "ssssss",
  "patronKel": "Kali Deres",
  "patronKec": "Kali Deres",
  "patronCity": "Jakarta Barat",
  "patronProvince": "DKI Jakarta",
  "patronSrcOfFund": "2",
  "patronYearlyIncome": "1",
  "patronOpenAccReason": "1",
  "patronJob": "09",
  "patronJobTitle": "01",
  "patronRelationship": "01",
  "patronPob": "Jakarta",
  "patronDob": "1990-01-01",
  "patronNationality": "ID",
  "patronMarriageStatus": "M",
  "patronCompany": "ssss",
  "patronCompanyAddress": "cxx",
  "patronCompanyAddress2": "aaa",
  "patronCompanyPhone": "021",
  "patronCompanyPostalCode": "10101",
  "patronMobileNum": "08156777766",
  "selfiePhoto": "",
  "idPhoto": "",
  "idSelfiePhoto": "",
  "signaturePhoto": "",
  "channelPromotionCode": "",
  "otp": "762592",
  "refNum" : "EFOR1266092981",
  "gender": "M",
  "tglLahirPemberiDana": "",
  "religion": "islam",
  "publisherCity": "publisherCity",
  "isMaried": "S",
  "jenisKelaminPemberiDana" : "M",
  "alamatLain" : "lain",
  "perumLain": "perumlain",
  "rtLainPemberiDana": "4",
  "rwLainPemberiDana": "5",
  "provinsiLainPemberiDana": "DKI Jakarta",
  "kabupatenLain": "Jakarta Barat",
  "kecamatanLainPemberiDana": "Cengkareng",
  "kelDesaLainPemberiDana": "Cengkarang Barat",
  "kodeposLain": "11730",
  "rtKerjaPemberiDana": "2",
  "rwKerjaPemberiDana": "3",
  "provinsiKerjaPemberiDana": "DKI Jakarta",
  "kabKerjaPemberiDana": "Jakarta Barat",
  "kecamatanKerjaPemberiDana": "Palmerah",
  "kelDesaKerjaPemberiDana": "Palmerah",
  "kodeposKerjaPemberiDana": "11480",
  "noTelp2KerjaPemberiDana": "434324",
  "komplekKerjaPemberiDana": "komplek",
  "adaNPWP": "1",
  "detailPekerjaan": "detailkerja",
  "namaTempatKerja": "kantor",
  "alamatTempatKerja2": "alaamtkerja2",
  "alamatTempatKerja": "tempatkerja",
  "kodePos": "11840"
}"""

r = requests.post("http://192.168.158.138:9101/eform/simpanan", json=json.loads(payload))
print(r.text)