<wsdl:definitions name="WSExport_IFCoreServiceHttp_Service" 
					targetNamespace="http://service.bni.co.id/core/Binding2" 
					xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
					xmlns:Port_0="http://service.bni.co.id/core" 
					xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
					xmlns:this="http://service.bni.co.id/core/Binding2">
   <wsdl:import location="IFCoreService.wsdl" namespace="http://service.bni.co.id/core"/>
   <wsdl:binding name="WSExport_IFCoreServiceHttpBinding" type="Port_0:IFCoreService">
      <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsdl:operation name="transaction">
         <soap:operation soapAction=""/>
         <wsdl:input name="transactionRequest">
            <soap:body use="literal"/>
         </wsdl:input>
         <wsdl:output name="transactionResponse">
            <soap:body use="literal"/>
         </wsdl:output>
         <wsdl:fault name="appFault">
            <soap:fault name="appFault" use="literal"/>
         </wsdl:fault>
         <wsdl:fault name="supFault">
            <soap:fault name="supFault" use="literal"/>
         </wsdl:fault>
         <wsdl:fault name="sysFault">
            <soap:fault name="sysFault" use="literal"/>
         </wsdl:fault>
      </wsdl:operation>
   </wsdl:binding>
   <wsdl:service name="WSExport_IFCoreServiceHttpService">
      <wsdl:port binding="this:WSExport_IFCoreServiceHttpBinding" name="WSExport_IFCoreServiceHttpPort">
         <soap:address location="http://192.168.143.61:57004/CoreService"/>
      </wsdl:port>
   </wsdl:service>
</wsdl:definitions>
