--------------------------------------------------------
--  DDL for Table BRANCHLESS_OPEN_ACCOUNTS
--------------------------------------------------------

  CREATE TABLE "SOA_APP"."BRANCHLESS_OPEN_ACCOUNTS" 
   (	"TIMESTAMP" TIMESTAMP (6), 
	"ACCOUNTNUM" VARCHAR2(20 BYTE), 
	"ACCOUNT_TYPE" VARCHAR2(4 BYTE), 
	"SUBCAT" VARCHAR2(4 BYTE), 
	"ACCOUNT_HOME_BRANCH" VARCHAR2(5 BYTE), 
	"CIFNUM" VARCHAR2(20 BYTE), 
	"ID_NUM" VARCHAR2(20 BYTE), 
	"ID_TYPE" VARCHAR2(5 BYTE), 
	"NATIONALITY" VARCHAR2(30 BYTE), 
	"CUSTOMER_NAME" VARCHAR2(100 BYTE), 
	"DOB" DATE, 
	"EMAIL" VARCHAR2(100 BYTE), 
	"HOME_PHONE" VARCHAR2(20 BYTE), 
	"MOBILENUM" VARCHAR2(20 BYTE), 
	"EDUCATION" VARCHAR2(10 BYTE), 
	"HOBBY" VARCHAR2(15 BYTE), 
	"OPEN_ACC_REASON" VARCHAR2(2 BYTE), 
	"SRC_OF_FUND" VARCHAR2(2 BYTE), 
	"PROJECTED_TRX" VARCHAR2(2 BYTE), 
	"NPWP_NUM" VARCHAR2(20 BYTE), 
	"ADDRESS" VARCHAR2(200 BYTE), 
	"RT" VARCHAR2(3 BYTE), 
	"RW" VARCHAR2(3 BYTE), 
	"KELURAHAN" VARCHAR2(60 BYTE), 
	"KECAMATAN" VARCHAR2(60 BYTE), 
	"CITY" VARCHAR2(60 BYTE), 
	"PROVINCE" VARCHAR2(60 BYTE), 
	"POSTAL_CODE" VARCHAR2(6 BYTE), 
	"JOB" VARCHAR2(20 BYTE), 
	"JOB_TITLE" VARCHAR2(15 BYTE), 
	"YEARLY_INCOME" VARCHAR2(20 BYTE), 
	"COMPANY_NAME" VARCHAR2(100 BYTE), 
	"COMPANY_ADDRESS" VARCHAR2(100 BYTE), 
	"COMPANY_ADDRESS2" VARCHAR2(100 BYTE), 
	"OFFICE_POSTAL_CODE" VARCHAR2(6 BYTE), 
	"START_WORK_DATE" DATE, 
	"OFFICE_PHONE" VARCHAR2(20 BYTE), 
	"PATRON_NAME" VARCHAR2(100 BYTE), 
	"PATRON_ID_TYPE" VARCHAR2(5 BYTE), 
	"PATRON_ID_NUM" VARCHAR2(20 BYTE), 
	"PATRON_NPWP_NUM" VARCHAR2(20 BYTE), 
	"PATRON_ADDRESS" VARCHAR2(100 BYTE), 
	"PATRON_RT" VARCHAR2(3 BYTE), 
	"PATRON_RW" VARCHAR2(3 BYTE), 
	"PATRON_BUILDING" VARCHAR2(50 BYTE), 
	"PATRON_KEL" VARCHAR2(60 BYTE), 
	"PATRON_KEC" VARCHAR2(60 BYTE), 
	"PATRON_CITY" VARCHAR2(60 BYTE), 
	"PATRON_PROVINCE" VARCHAR2(60 BYTE), 
	"PATRON_SRC_OF_FUND" VARCHAR2(2 BYTE), 
	"PATRON_YEARLY_INCOME" VARCHAR2(20 BYTE), 
	"PATRON_OPEN_ACC_REASON" VARCHAR2(2 BYTE), 
	"PATRON_JOB" VARCHAR2(20 BYTE), 
	"PATRON_JOB_TITLE" VARCHAR2(15 BYTE), 
	"PATRON_RELATIONSHIP" VARCHAR2(20 BYTE), 
	"PATRON_POB" VARCHAR2(30 BYTE), 
	"PATRON_DOB" DATE, 
	"PATRON_NATIONALITY" VARCHAR2(30 BYTE), 
	"PATRON_MARRIAGE_STATUS" VARCHAR2(30 BYTE), 
	"PATRON_COMPANY_NAME" VARCHAR2(100 BYTE), 
	"PATRON_COMPANY_ADDRESS" VARCHAR2(100 BYTE), 
	"PATRON_COMPANY_ADDRESS2" VARCHAR2(100 BYTE), 
	"PATRON_OFFICE_POSTAL_CODE" VARCHAR2(6 BYTE), 
	"PATRON_MOBILE_NUM" VARCHAR2(20 BYTE), 
	"FLAG" VARCHAR2(6 BYTE), 
	"CHANNEL" VARCHAR2(60 BYTE), 
	"ID_PHOTO" VARCHAR2(30 BYTE), 
	"CUST_PHOTO" VARCHAR2(30 BYTE), 
	"CUST_WITH_ID_PHOTO" VARCHAR2(30 BYTE), 
	"STATUS" VARCHAR2(10 BYTE), 
	"ERRORCODE" VARCHAR2(20 BYTE), 
	"ERRORMESSAGE" VARCHAR2(100 BYTE), 
	"LAST_UPDATE" TIMESTAMP (6), 
	"REFNUM" VARCHAR2(16 BYTE), 
	"CHANNELPROMOCODE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_WSRR" ;
--------------------------------------------------------
--  DDL for Index BRANCHLESS_OPEN_ACCOUNTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOA_APP"."BRANCHLESS_OPEN_ACCOUNTS_PK" ON "SOA_APP"."BRANCHLESS_OPEN_ACCOUNTS" ("ID_NUM", "ID_TYPE", "MOBILENUM", "REFNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_WSRR" ;
--------------------------------------------------------
--  Constraints for Table BRANCHLESS_OPEN_ACCOUNTS
--------------------------------------------------------

  ALTER TABLE "SOA_APP"."BRANCHLESS_OPEN_ACCOUNTS" MODIFY ("ID_NUM" NOT NULL ENABLE);
  ALTER TABLE "SOA_APP"."BRANCHLESS_OPEN_ACCOUNTS" MODIFY ("ID_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SOA_APP"."BRANCHLESS_OPEN_ACCOUNTS" MODIFY ("MOBILENUM" NOT NULL ENABLE);
  ALTER TABLE "SOA_APP"."BRANCHLESS_OPEN_ACCOUNTS" MODIFY ("REFNUM" NOT NULL ENABLE);
  ALTER TABLE "SOA_APP"."BRANCHLESS_OPEN_ACCOUNTS" ADD CONSTRAINT "BRANCHLESS_OPEN_ACCOUNTS_PK" PRIMARY KEY ("ID_NUM", "ID_TYPE", "MOBILENUM", "REFNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_WSRR"  ENABLE;
