<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="BancslinkTransactionHttp_Service" targetNamespace="http://service.bni.co.id/bancslink" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:this="http://service.bni.co.id/bancslink" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import location="BancslinkTransaction.wsdl" namespace="http://service.bni.co.id/bancslink"/>
  <wsdl:binding name="BancslinkTransactionHttpBinding" type="this:BancslinkTransaction">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="transaction">
      <soap:operation soapAction=""/>
      <wsdl:input name="transactionRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="transactionResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="BancslinkTransactionHttpService">
    <wsdl:port binding="this:BancslinkTransactionHttpBinding" name="BancslinkTransactionHttpPort">
      <soap:address location="http://192.168.143.61:57007/ChannelService"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>