from pydantic import BaseModel
class CreateAccountRequest(BaseModel):
    channel: str
    tellerId: str
    accountNum: str
    branch: str
    accountType: str
    subCat: str
    othersOpenAccReason: str
    othersSrcOfFund: str
    idNum: str
    idType: str
    customerName: str
    pob: str
    dateOfBirth: str
    motherMaidenName: str
    email: str
    homePhone: str
    mobileNum: str
    education: str
    hobby: str
    openAccReason: str
    srcOfFund: str
    projDep: str
    taxId: str
    customerAddress: str
    rt: str
    rw: str
    kelurahan: str
    kecamatan: str
    city: str
    province: str
    postalCode: str
    job: str
    yearlyIncome: str
    companyName: str
    companyAddress: str
    companyAddress2: str
    officePostalCode: str
    jobTitle: str
    startWorkDate: str
    officePhone: str
    patronName: str
    patronIdType: str
    patronIdNum: str
    patronTaxId: str
    patronAddress: str
    patronRt: str
    patronRw: str
    patronBuilding: str
    patronKel: str
    patronKec: str
    patronCity:str
    patronProvince: str
    patronSrcOfFund: str
    patronYearlyIncome: str
    patronOpenAccReason: str
    patronJob: str
    patronJobTitle: str
    patronRelationship: str
    patronPob: str
    patronDob: str
    patronNationality: str
    patronMarriageStatus: str
    patronCompany: str
    patronCompanyAddress: str
    patronCompanyAddress2: str
    patronCompanyPhone: str
    patronCompanyPostalCode: str
    patronMobileNum: str
    selfiePhoto: str
    idPhoto: str
    idSelfiePhoto: str
    signaturePhoto: str
    channelPromotionCode: str
    otp: str
    refNum: str
    gender: str
    religion: str
    isMaried: str
    publisherCity: str
    detailPekerjaan: str
    namaTempatKerja: str
    alamatTempatKerja: str
    alamatTempatKerja2: str
    kodePos: str
    alamatLain: str
    perumLain: str
    rtLainPemberiDana: str
    rwLainPemberiDana: str
    provinsiLainPemberiDana: str
    kabupatenLain: str
    kecamatanLainPemberiDana: str
    kelDesaLainPemberiDana: str
    kodeposLain: str
    komplekKerjaPemberiDana: str
    rtKerjaPemberiDana: str
    rwKerjaPemberiDana: str
    provinsiKerjaPemberiDana: str
    kabKerjaPemberiDana: str
    kecamatanKerjaPemberiDana: str
    kelDesaKerjaPemberiDana: str
    kodeposKerjaPemberiDana: str
    noTelp2KerjaPemberiDana: str
    adaNPWP: str
    jenisKelaminPemberiDana: str
    tglLahirPemberiDana: str